services:
  nasa-api-front-vue3:
    container_name: nasa-api-front-vue3
    ports:
      - "8081:8081"
    networks:
      - rpi-network

volumes:
  postgres_data:

networks:
  rpi-network:
    external: true
