server {
    listen 80;
    server_name localhost;

    # Localização padrão para servir a aplicação Vue
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o backend
    # Qualquer chamada para /api/... será redirecionada
    location /api/ {
        # O Nginx vai passar a requisição para o backend
        proxy_pass http://nasa-api-backend:8080/api/;

        # Cabeçalhos importantes para o proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}