name: Deploy Vue 3 App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Deploy manual

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # Especifica o environment "production" para este job

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Vue.js app
      run: npm run build

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production  # Especifica o environment "production" para este job
    if: github.event_name == 'workflow_dispatch'  # Executa o deploy apenas manualmente

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        script: |
          mkdir -p /home/ubuntu/vue3-app
          cd /home/ubuntu/vue3-app
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest
          docker run -d -p 5173:80 ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest
