name: Deploy Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Deploy manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to Raspberry Pi via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.RASPBERRY_PI_HOST }}  # Adicione o host do Raspberry Pi nos secrets do repositório
        username: ${{ secrets.RASPBERRY_PI_USER }}  # Usuário configurado para o SSH no Raspberry Pi
        key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}  # Chave SSH privada do Raspberry Pi adicionada nos secrets
        port: 22  # Porta padrão para SSH
        script: |
          mkdir -p /home/pi/vue3-app  # Ajuste o caminho conforme necessário
          cd /home/pi/vue3-app
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest
          docker run -d -p 5173:80 ${{ secrets.DOCKER_USERNAME }}/nasa-api-front-vue3:latest